'''

## Prompts in LangChain

Prompts define **how input is structured before sending it to the LLM**.
LangChain provides different prompt types depending on the **complexity of the interaction**.

---

# 1. Text Prompt

**Definition**

A **Text Prompt** is a simple string-based prompt sent directly to the LLM.

It is ideal for **straightforward text generation tasks** where you **do not need to maintain conversation history or message roles**.

**Characteristics**

* Uses **plain text input**
* Best for **single-turn tasks**
* **Minimal code complexity**
* No separation between system, user, or assistant messages
* Faster and simpler for small pipelines

**When to Use**

* Summarization
* Text generation
* Translation
* Simple Q&A
* One-time instructions

**Example**

```python
from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate.from_template(
    "Explain {topic} in simple terms"
)

prompt.invoke({"topic": "LangChain"})
```

Here the model receives a **single formatted text string**.

---

# 2. Message Prompts (Chat Prompts)

**Definition**

Message prompts are used when interacting with **chat-based models**.
Instead of a single string, the prompt is structured as **a list of messages with specific roles**.

This allows the model to **understand conversation context and role separation**.

**Advantages**

* Supports **conversation history**
* Enables **role-based instructions**
* Useful for **agents and tool calling**
* Better control over model behavior

---

## Types of Messages

### 1. System Message

Defines the **overall behavior or rules** for the AI.

Example roles:

* Setting the assistant personality
* Defining instructions
* Restricting model behavior

Example

```python
SystemMessage(content="You are a helpful programming assistant.")
```

---

### 2. Human Message

Represents **input from the user**.

Example

```python
HumanMessage(content="Explain what LangChain is.")
```

---

### 3. AI Message

Represents **the response generated by the AI model**.

Used mainly when **storing conversation history**.

Example

```python
AIMessage(content="LangChain is a framework for building LLM applications.")
```

---

### 4. Tool Message

Used when **tools are called during agent execution**.

It contains the **result returned by a tool** which is then sent back to the model.

Example

```python
ToolMessage(content="Weather is 30°C", tool_name="weather_tool")
```

---

## Example of Message Prompt

```python
from langchain_core.messages import SystemMessage, HumanMessage

messages = [
    SystemMessage(content="You are a helpful AI tutor."),
    HumanMessage(content="Explain recursion simply")
]
```

Here the model receives **structured conversation messages instead of plain text**.

---

## Text Prompt vs Message Prompt

| Feature              | Text Prompt   | Message Prompt       |
| -------------------- | ------------- | -------------------- |
| Structure            | Plain text    | Role-based messages  |
| Complexity           | Simple        | More structured      |
| Conversation history | Not supported | Supported            |
| Best for             | Single tasks  | Chat systems, agents |
| Code complexity      | Minimal       | Slightly higher      |

---

✔ **Summary**

* **Text Prompt** → Simple, single-turn tasks with minimal complexity.
* **Message Prompt** → Structured chat interactions with roles like system, human, AI, and tools.

---
'''
